### ISSUE TITLE
TypeError: list indices must be integers or slices, not float

### ISSUE THREAD

**Issue by hktxt** [tsoding/kdtree-in-python#1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-d7bf3bb93777> in <module>()
----> 1 kdtree = build_kdtree(points)

<ipython-input-12-117060445a8d> in build_kdtree(points, depth)
     10 
     11     return {
---> 12         'point': sorted_points[n / 2],
     13         'left': build_kdtree(sorted_points[:n / 2], depth + 1),
     14         'right': build_kdtree(sorted_points[n/2 + 1:], depth + 1)

TypeError: list indices must be integers or slices, not float

**Comment by Minoru** [comment]
Hi! Apparently the code is written in Python 2, where `/` is integer division (where 4 / 3 = 1), but you're running it with Python 3 where `/` is floating-point division (where 4 / 3 = 1.3333333).

Luckily, [there is a non-ambiguous operator `//`](http://python3porting.com/preparing.html#division-section) which performs integer division in both Python 2 and 3. Use it instead of `/`, and maybe even submit a pull request here so noone else has to deal with that problem ever again.

**Comment by hktxt** [comment]
@Minoru thanks~
